name: Performance Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Cada día a las 02:00 AM
  workflow_dispatch:

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Performance Tests
        run: mvn -Pperformance integration-test

      - name: Move performance reports to site folder
        run: mvn -Pperformance resources:copy-resources@copy-perf-report

      - name: Copy performance reports to docs
        run: |
          mkdir -p docs/site/reports
          cp -r target/reports/* docs/site/reports/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
